### ISSUE TITLE
[BUG] Crash on Task Preview

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#115]
### Issue description:
Crashes on win while pressing `Task Preview` button.

reported by: @slatunje

### Environment:
* **Application version**: 0.3.2
* **Blender client version**: 2.90.0
* **OS**: Win10

### Steps to reproduce:
1. Run Blender
2. Open project
3. Run the rendering on BlendNet
4. Click `Task Preview`
5. Blender crashes

### Additional context
Restart the blender on Windows helps to get the task preview, but looks like on mac it continues to fail.

### Workaround
Seems only blender >= 2.90 is affected, so downgrade to 2.83 LTS helps.

**Comment by rabits** [comment]
Yeah, on win it's quite easy to reproduce:
* [test-project.crash.txt](https://github.com/state-of-the-art/BlendNet/files/5398370/test-project.crash.txt)
* [test-project.stdout.txt](https://github.com/state-of-the-art/BlendNet/files/5398371/test-project.stdout.txt)

**Comment by rabits** [comment]
Made some debug work and looks like win platform doesn't allow to sleep or request something that requires waiting. So the render process there should be quick and not to block the thread anyhow.

**Comment by rabits** [comment]
So I think it's possible to move all the time-consuming operations to a separated thread and just use the available variable data to update the render instantly.

**Comment by slatunje** [comment]
[cube.blend.log](https://github.com/state-of-the-art/BlendNet/files/5399743/cube.blend.log)
[cube.crash.txt](https://github.com/state-of-the-art/BlendNet/files/5399744/cube.crash.txt)

So this happened again adding logs

**Comment by rabits** [comment]
> [cube.blend.log](https://github.com/state-of-the-art/BlendNet/files/5399743/cube.blend.log)
> [cube.crash.txt](https://github.com/state-of-the-art/BlendNet/files/5399744/cube.crash.txt)
> 
> So this happened again adding logs

Looks like not related to the current issue - it seems like your custom script issue:
```
bpy.ops.text.run_script()  # Operator
  File "/Users/USER/Desktop/@Blender/Clouds/cube/cube.blend/preferences_user", line 3
    bpy.context.user_preferences.addons['cycles'].preferences.compute_device_type = 'CUDA'
```
Just take a closer look at the logs you're attached.

**Comment by rabits** [comment]
Slightly reorganized the render pipeline, but on windows it still generates the crash, but slightly different one...
<details><summary>test-project.stdout.txt</summary>
DEBUG: Periodic update manager info True
DEBUG: Init BlendNet render
GPUFrameBuffer: framebuffer status GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
Warning, attempting to detach Texture 00000202C6D194E0 from framebuffer 00000202C6952388 but texture is not attached.
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6649175D6
Module  : blender.exe
Thread  : 00001944
Writing: C:\Users\user\AppData\Local\Temp\test-project.crash.txt
INFO: Render status: , testproject-2010172304-32-q7S: COMPLETED
INFO: Render status: Got the final result: C:\Users\user\Documents\BlendNet-test-project-2.82-v0.4\proj\out0032.png | Task render time: 13m35s, testproject-2010172304-32-q7S: COMPLETED
</details>
[test-project.crash.txt](https://github.com/state-of-the-art/BlendNet/files/5405001/test-project.crash.txt)

Will check on the other versions and seems it needed to be reported to Blender team - it's not a good behavior for sure.

**Comment by rabits** [comment]
Yeah, on 2.83.7 it's working well - so reporting to Blender team.

**Comment by rabits** [comment]
Added the ticket for blender devs: https://developer.blender.org/T81872

This task will be about moving download to background, if it's really needed.

**Comment by rabits** [comment]
Looks like the issue with the crash is about the engine change in the render thread. So I think I need to move it outside the render process and it will work well.

Unfortunately it's quite hard to make the minimal implementation - maybe there is some hidden processes that causing the crash, but anyway the point is to make blendnet addon work and not to wait until the issue with crash will be fixed on blender side.
