### ISSUE TITLE
[FEATURE] Animation task

### ISSUE THREAD

**Issue by gponceau** [state-of-the-art/BlendNet#120]
### Is your feature request related to a problem? Please describe.
I'm not sure if there already is on the release schedule. When I run an animation task, I have so many task, wich one corresponds to a single frame.

### Describe the solution you'd like
Is it to possible to have one task per animation ?

### Additional context
I'm using Blender 2.90.1 with Blendnet 0.3.3 on Windows 10

**Comment by rabits** [comment]
I think it related to #112 - BlendNet operates with frame tasks, so it's just matter of UI to group them properly and show in easy way for the user.
