### ISSUE TITLE
[BUG] Blender zip addon installation/activation fails

### ISSUE THREAD

**Issue by Raptoaaah** [state-of-the-art/BlendNet#123]
### Issue description:
The plugin fails to activate after importing the .zip of the plugin.

### Environment:
* **Application version**: 0.3.3
* **Blender client version**: 2.91.0
* **Blender worker version**: n.A.
* **OS**: MacOS 11.0.1

### Steps to reproduce:
1. Run Blender
2. Open Preferences
3. Go to Add-ons
4. Click install
5. Select .zip of the plugin
6. Activate the plugin
7. Error

### Expected behavior
Plugin activates

### Screenshots
<img width="676" alt="Bildschirmfoto 2020-11-27 um 08 36 08" src="https://user-images.githubusercontent.com/18486085/100423374-2dfc5b80-308c-11eb-9cbe-ebbc09b1b1d3.png">

### Additional context
Case-sensitive file system used

**Comment by rabits** [comment]
Yep blender don't like addon fiolders that contains some dots, if you're trying to use release auto-generated zip archives from github - that will not work. Please use release CI-prepared archives:

![screenshot](https://user-images.githubusercontent.com/1093323/100479466-314f1180-30a3-11eb-8dc8-93173db33749.png)

**Comment by rabits** [comment]
From blender perspective: you can try to create a ticket for the blender folks, but I think versioning of the addon folders is not a great thing - so they just need to warn it properly, like "dots are not allowed in the addon folder name - please don't use versioned folders for the addons".

From github perspective: looks like github uses `git archive` command to create `Source code (.fmt)` which can be slightly adjusted via `.gitattributes` (#124) - but it don't control the prefix, so not much I can do there... Created the [github community request](https://github.community/t/control-prefix-of-the-release-source-code/145808) about that.

**Comment by rabits** [comment]
BTW please use just released [BlendNet v0.3.4](https://github.com/state-of-the-art/BlendNet/releases/tag/v0.3.4) if you're planning to to run on Blender 2.91.0.

**Comment by Raptoaaah** [comment]
Thank you for the quick solution! Seemingly this was the problem for me, now it works.
Thanks a lot :)
