### ISSUE TITLE
[BUG] Upload struggles to reach the agent

### ISSUE THREAD

**Issue by Raptoaaah** [state-of-the-art/BlendNet#127]
### Issue description:
After starting the render job the render process is stuck at CREATED and changes to ERROR after some time while the UI gets unresponsive.

### Environment:
* **Application version**: 0.3.4
* **Blender client version**: 2.91.0
* **Blender worker version**: 2.91.0
* **OS**: MacOS 11.0.1

### Steps to reproduce:
1. Run Blender
2. Open project
3. Click on 'Run image ...'
4. Task gets created and shows CREATED
5. After a while it changes to ERROR with the message "path to xyz.blend is not absolute"

What happens on the console:
Manager:
- "PUT /api/v1/task/xyz-.../file/xyz.blend HTTP/1.1" 200
- "PUT /api/v1/task/xyz-.../config HTTP/1.1" 400
Agent:
- Only GET status in log
- Something in the blob folder gets created

### Expected behavior
Render job gets executed

### Additional context
Manager and Agent installed according to wiki with no visible error on any log and included in Blender with status messages as expected until some job is started.
After pressing "Run image ..." the UI gets unresponsive. To get the status Blender has to be restarted and then the job error can be read out and then the job also can be deleted.
The Agent and the Manager are running with their own respective users with their own respective workspace on different machines in the same network, all based on a recent Linux.

**Comment by rabits** [comment]
Hi @Raptoaaah , thank you for the report) Seems we will need the logs to check what's happened. Could you please follow the wiki page: https://github.com/state-of-the-art/BlendNet/wiki/If-you-stuck-with-an-issue and attach the Manager log.

The error overall is about the task configuration process and should not fail under usual circumstances, but seems there is a bug with uploading. Hopefully the logs will be helpful.

**Comment by Raptoaaah** [comment]
Thank you for your reply, I created a dump of the whole manager console printout. If you need something different, I try to do whatever possible.
If you need additional information of the current state of the program I can also add additional printout in the code.
[manager.log](https://github.com/state-of-the-art/BlendNet/files/5611847/manager.log)

**Comment by rabits** [comment]
Hmmm, yeah, it tried to send config multiple times with no luck. Could you also please attach the Blender Client log: just run it in terminal for example and try to send the same blend file to the Manager.

**Comment by Raptoaaah** [comment]
I have a look at the code in parallel, maybe I find some point where something could go wrong or additional printout may be helpful

I tried to reproduce as close as possible
[client.log](https://github.com/state-of-the-art/BlendNet/files/5611874/client.log)

**Comment by Raptoaaah** [comment]
Sry, this was the agent log >.<

the log of the blender client comes here

[client.log](https://github.com/state-of-the-art/BlendNet/files/5611898/client.log)

**Comment by Raptoaaah** [comment]
I found a solution for my problem
There seems to be a change in the REST interface in the current git
To get easy updates I decided to just git clone for my servers, with the release version it seems to work fine

**Comment by rabits** [comment]
Oh, you mean you used not the same versions for Client/Manager BlendNet? Or just updated to the current master branch 0.4.0-dev?

**Comment by rabits** [comment]
Yeah, so you can get the error "Error during task files fixing" only if your BlendNet Manager is `v0.4.0-dev`. and it's incompatible with `v0.3` under certain circumstances (#102). So make sure you using the same version for Client, Manager and Agent sides and you will be good.

**Comment by Raptoaaah** [comment]
I used 0.3.4 for the BlendNet Addon and master branch for manager and agent and this failed
Currently the 0.3.4 release version seems to work if used consistently throughout the whole system, so yeah, this solves the problem
Thank you for your support :)

**Comment by rabits** [comment]
Great!) Thank you - I will add this note to the wiki.
