### ISSUE TITLE
[BUG] InvalidURL("URL can't contain control characters")

### ISSUE THREAD

**Issue by meermanr** [state-of-the-art/BlendNet#130]
### Issue description:

After setting up a local manager + 3x agents in my home LAN and getting them all connected to a Blender GUI instance the "Run Image Task" displays a status message:

    Uploading process 2 task BackBedroommeasured-2012270151-1-6Zy: left to upload...

After many minutes this has not changed, which is odd as my scene does not use a single texture. So I restarted Blender from a terminal so I can see STDOUT / STDERR, where the following error is displayed over and over:

    ERROR: Communication exception - check the remote service for errors "https://Roberts-MBP.lan:8443/api/v1/task/BackBedroommeasured-2012270151-1-6Zy/file/reference/Pax Wardrobe mirror.png": (<class 'http.client.InvalidURL'>, InvalidURL("URL can't contain control characters. '/api/v1/task/BackBedroommeasured-2012270151-1-6Zy/file/reference/Pax Wardrobe mirror.png' (found at least ' ')"), <traceback object at 0x128ce2460>)
    WARN: Uploading of "reference/Pax Wardrobe mirror.png" to task "BackBedroommeasured-2012270151-1-6Zy" failed, repeating...
    
So it appears that an image I had loaded into an Image Editor pane is being uploaded as part of the scene, even though it is not used by any shaders (etc), and that the spaces in the names are causing issues.

Presumably the URL should be URI encoded, i.e. spaces become `%20`?

### Environment:
* **Application version**: `blendnet-0.3.5.zip`
* **Blender client version**: 2.91.0 (Darwin)
* **Blender worker version**: 2.91.0 (Darwin)
* **OS**: MacOS (Darwin) 10.15.7 (Manager) and 11.1 (Agents)

### Steps to reproduce:
1. Run Blender from a command line (so STDOUT/STDERR are visible)
2. Keep default cube/scene open
3. Change 3D Viewport pane to "Image Editor"
4. In the menu bar, click "Image", then "Open"
5. Select a file with space in the name, e.g. `two words.png`
6. Go to render tab in Outliner
7. Set Render Engine to "Cycles"
8. Click "Run Image Task" within "BlendNet Render (local)"
9. See errors on STDOUT / STDERR

### Expected behavior
- Image would not be uploaded, as not required for rendering
- OR: Image uploads without error, because all modern OS support spaces and Unicode in file names

### Screenshots
(None included)

**Comment by rabits** [comment]
Hi @meermanr , yeah you right - seems I missed urlencode there. Will check closely.

**Comment by rabits** [comment]
@meermanr could you please check this fix: https://1069-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.6-4561301.zip ([just one line change](https://github.com/state-of-the-art/BlendNet/pull/131/files)), you will need to update Addon and Manager part of BlendNet setup and restart them - hopefully it will work fine)

**Comment by rabits** [comment]
Oh sorry, my bad - there is a mistake, so will rewrite the fix.

**Comment by rabits** [comment]
Ok, now it's perfect) https://1073-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.6-27de9c6.zip, will change the previous link to not confuse.

**Comment by meermanr** [comment]
Hi @rabits, that does indeed seem to have fixed it, thanks!

**Comment by rabits** [comment]
Great, merged.
