### ISSUE TITLE
[BUG] Add MacOS AWS specific info

### ISSUE THREAD

**Issue by willpuckett** [state-of-the-art/BlendNet#142]
### Issue description:
If it's a question - it's better to ask here: https://gitter.im/state-of-the-art/BlendNet

The AWS binary is not in the default MacOS path, preventing BlendNet from finding the binary upon Blender startup.

### Environment:
* **Application version**: [e.g. 0.2.0]
* **Blender client version**: [e.g. 2.83.0 (where addon is running)]
* **Blender worker version**: [e.g. 2.83.0 (which is used for manager/agents)]
* **OS**: [e.g. Ubuntu 18.04]

BlendNet 0.3
Blender 2.91.2

### Steps to reproduce:
1. Run Blender
2. Open project
3. Click on '....'
4. Scroll down to '....'
5. See error

### Additional context
Please check https://github.com/state-of-the-art/BlendNet/wiki/If-you-stuck-with-an-issue to attach
some useful logs here.

This is less a bug request and more a request to add the following info to the AWS config Wiki page to make it easier for others to get started. 

"BlendNet may not be able to locate the aws binary in a default MacOS install.

If the aws binary is in your $PATH set by .bash_profile or .bashrc, you can simply start blender from the command line and it will have access to the correct path variable. 

Otherwise, you can follow the instructions for changing lanuchctl configuration [here](https://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks)."

**Comment by rabits** [comment]
Yeah, so in v0.4 there will be ([already in master branch](https://github.com/state-of-the-art/BlendNet/issues/62)) the interface to set the path. Unfortunately it's too huge change for 0.3, but I added this to the wiki:
* AWS: https://github.com/state-of-the-art/BlendNet/wiki/HOWTO:-Setup-provider:-Amazon-Web-Services-(AWS)#macos-notice
* GCP: https://github.com/state-of-the-art/BlendNet/wiki/HOWTO:-Setup-provider:-Google-Cloud-Platform-(GCP)#macos-notice

Will it work?

**Comment by willpuckett** [comment]
That looks great! I might add, "or simply launch the app from the terminal" at the end just so noons have an easy workaround before v0.4.

Thanks for all the hard work your add on is awesome 😎 

Cheers,
WP

**Comment by rabits** [comment]
Sealed and done) Thank you for the input)
