### ISSUE TITLE
[BUG] Unable to load "gcp" provider due to init error

### ISSUE THREAD

**Issue by jarofghosts** [state-of-the-art/BlendNet#150]
### Issue description:
GCP provider throws error `Unable to load "gcp" provider due to init error: module 'googlecloudsdk.core.credentials.store' has no attribute 'DevShellCredentialProvider'` when trying to start up. Seems to be caused by [this line](https://github.com/state-of-the-art/BlendNet/blob/master/BlendNet/providers/gcp/__init__.py#L143)

### Environment:
* **Application version**: 0.3.8
* **Blender client version**: 2.92.0
* **Blender worker version**: 2.92.0
* **OS**: MacOS 10.15.7

### Steps to reproduce:
1. Set up gcp as outlined in the README (great docs, btw!)
2. Launch Blender from command line
3. Click on Addons > Blendnet

### Expected behavior
I expect the addon to load my gcloud credentials.

### Screenshots

![image](https://user-images.githubusercontent.com/1013892/113044419-774fdb00-9152-11eb-966b-688fd1ac9343.png)

### Additional context
```
Read prefs: /Users/jessekeane/Library/Application Support/Blender/2.92/config/userpref.blend
INFO: Found provider "gcp"
INFO: Found google cloud sdk: /Users/jessekeane/Downloads/google-cloud-sdk
DEBUG: Loading gcloud paths
WARN: Unable to load "gcp" provider due to init error: module 'googlecloudsdk.core.credentials.store' has no attribute 'DevShellCredentialProvider'
```

**Comment by rabits** [comment]
Hmmm, maybe the thing I was afraid of happened - they changed the SDK! Will check how to fix that.

For now as a workaround I can propose to use the older version of gcloud SDK: according to the changes tracker the last supported version is 329.0.0 https://github.com/twistedpair/google-cloud-sdk/blob/329.0.0/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py#L274

**Comment by jarofghosts** [comment]
That works for now, thanks a ton!

**Comment by jarofghosts** [comment]
Unfortunately while this got me to the point of being able to attempt to start the manager, every time I try to start it it fails. I notice in the logs it has a similar error:
```
Apr  2 01:30:41 blendnet-a0idgg-manager blender[2156]: INFO: Found provider "gcp"
Apr  2 01:30:41 blendnet-a0idgg-manager blender[2156]: INFO: Found google cloud sdk: /usr/lib/google-cloud-sdk
Apr  2 01:30:41 blendnet-a0idgg-manager blender[2156]: DEBUG: Loading gcloud paths
Apr  2 01:30:41 blendnet-a0idgg-manager blender[2156]: WARN: Unable to load "gcp" provider due to init error: module 'googlecloudsdk.core.credentials.store' has no attribute 'DevShellCredentialProvider'
```
not sure if this is why, but the addon can never connect to the manager

**Comment by rabits** [comment]
Oh no! I completely forgot about the Manager side! The thing here - it uses exactly the same logic as the Addon side, but the image there is the fresh one: https://github.com/state-of-the-art/BlendNet/blob/v0.3/BlendNet/providers/gcp/__init__.py#L303 and contains the latest gcloud SDK tools...

So as a workaround you can use some specific debian-10 image, but I think it's quite too much for the workaround, so tomorrow I will work on this issue and hopefully will find some solution)

**Comment by rabits** [comment]
@jarofghosts ok, looks like they just removed the `DevShellCredentialProvider` and now `GceCredentialProvider` serves it - could you please check that the fix is working for you: https://1517-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.9-5f7f0a7.zip

**Comment by jarofghosts** [comment]
@rabits yep, looks like that's working 👍

**Comment by rabits** [comment]
Great! Merged & sealed) Will release a new version v0.3.9 soon.

**Comment by jarofghosts** [comment]
@rabits confirmed everything seems to be working great now, thanks!!

**Comment by rabits** [comment]
Ok, so closing the issue. The new release is here: https://github.com/state-of-the-art/BlendNet/releases/tag/v0.3.9
