### ISSUE TITLE
[FEATURE] Support Windows as a blender client platform to submit render tasks

### ISSUE THREAD

**Issue by blender80** [state-of-the-art/BlendNet#16]
Right now the source code expects blender to run on a posix OS causing it to fail when locating gcloud command or scrambles paths while uploading files to the cloud storage bucket ("\" vs "/" in file paths). 

Adding better windows support will increase the audience for this great addon.

**Comment by rabits** [comment]
Hi @blender80 

Thank you for the investigation, yeah for sure it's needed and hopefully soon we will work on windows support.

Thank you

**Comment by blender80** [comment]
Hi, I have a fix ready, but can't submit. Still learning github. When I tried to submit I got an access denied. I can email you the files of you want.Also happy to learn how to properly so thisCheers   -- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 5/6/20, 8:12 PM Rabit <notifications@github.com> wrote:

   
  Hi @blender80 
  Thank you for the investigation, yeah for sure it's needed and hopefully soon we will work on windows support. 
  Thank you

**Comment by rabits** [comment]
Oh, if you have fix - so yousually gihub workflow looks like: you need to fork the repo to your account, push changes to your forked master or any other branch and create pull-request to the original repository.

**Comment by blender80** [comment]
Ok,

 

I have managed at least the fork and submitting my change:

https://github.com/blumem/BlendNet

 

(it is only affecting //BlendNet/providers/gcp/__init__.py)

 

Not sure yet about how to do the pull-request to the original repository. Still learning git.

 

Also, I had to read up on some legal stuff. I'm working for Google (not for compute engine, but somewhere in GSuite and was only interested in this for personal blender hobby reasons), but my employment contract says that I need to do all software work including Open Source work in my free time under Copy Right to Google. Hence, I had to insert the two lines in the header at the top. 

 

 Feel free to perform the merge/pull if you like the changes.

 

My next undertaking is to investigate problems in uploading larger projects (350mb file). 

 

I get the following error when trying to render an animation:

WARN: Uploading of "cgkookie_rain_on_wet_road_2ndattempt_packed_smalltiles.blend" to task "cgkookierainonwetroad2ndattemptpackedsmalltiles-2005071039-51-GWF" failed, repeating...
WARN: Communication issue with request to "https://<manager-ip>:8443/api/v1/task/cgkookierainonwetroad2ndattemptpackedsmalltiles-2005071039-51-GWF/file/cgkookie_rain_on_wet_road_2ndattempt_packed_smalltiles.blend": [WinError 10053] An established connection was aborted by the software in your host machine

 

I assume that somehow the server closes the connection during upload?

 

Any hints welcome

 


Gesendet: Donnerstag, 07. Mai 2020 um 00:57 Uhr
Von: "Rabit" <notifications@github.com>
An: "state-of-the-art/BlendNet" <BlendNet@noreply.github.com>
Cc: "blender80" <blume.michael@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [state-of-the-art/BlendNet] [FEATURE] Support Windows as a blender client platform to submit render tasks (#16)


 

Oh, if you have fix - so yousually gihub workflow looks like: you need to fork the repo to your account, push changes to your forked master or any other branch and create pull-request to the original repository.

**Comment by rabits** [comment]
Yeah, that's better to read the manual to figure out the github workflow: https://guides.github.com/activities/forking/ - that will be much better if you can create the PR.

About the legal - better to check with your manager or Google legal team. Not sure that Google could anyhow restrict your opensource activities if you doing them in your free time (during your usual duties - probably).

About the issue you see - unfortunately it contains not enough information... Better to wait until the logic will be merged to master and create the additional issue to track it.

**Comment by blender80** [comment]
Awesome,

 

thanks for the quick answer and the pointer to the documentation. I have created a pull request, hope it works. If I understand correctly it is you who should review and confirm the merge? Or am I supposed to self approve? (At work we can only submit after peer approval). 

 

Confirmed with legal, my contract binds "my soul to the company" meaning all software engineering work I do is claimed by the company. It is what it is...

 

I'm trying variances now with different sizes, namings and complexities to see if I can isolate the problem.

 
 

Gesendet: Freitag, 08. Mai 2020 um 03:06 Uhr
Von: "Rabit" <notifications@github.com>
An: "state-of-the-art/BlendNet" <BlendNet@noreply.github.com>
Cc: "blender80" <blume.michael@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [state-of-the-art/BlendNet] [FEATURE] Support Windows as a blender client platform to submit render tasks (#16)


 

Yeah, that's better to read the manual to figure out the github workflow: https://guides.github.com/activities/forking/ - that will be much better if you can create the PR.

About the legal - better to check with your manager or Google legal team. Not sure that Google could anyhow restrict your opensource activities if you doing them in your free time (during your usual duties - probably).

About the issue you see - unfortunately it contains not enough information... Better to wait until the logic will be merged to master and create the additional issue to track it.

**Comment by rabits** [comment]
Thank you for the contribution - the change just merged: #17
