### ISSUE TITLE
[BUG] Default cube scene can't be composed properly

### ISSUE THREAD

**Issue by Zman350x** [state-of-the-art/BlendNet#160]
### Issue description:
As I'm rendering over BlendNet (local provider), I'm getting "E:100:00%" instead of "COMPLETED" by each task. It's also taking way longer than I'd expect given the number/power of local agents. I've tried with 14 agents over WiFi, which never even got to the point where each task said "E:100:00%," most likely due to network issues. I've also tried with 3 agents over Ethernet, which at least completed all tasks with the "E:100:00%" error.

### Environment:
* **Application version**: v0.3.10
* **Blender client version**: v3.0.0
* **Blender worker version**: v3.0.0
* **OS**: Windows 10 Home x64 version 2004 (on all PCs)

### Steps to reproduce:
1. Run Blender
2. Keyframe default cube's z-rotation to 0 on frame one. Keyframe it to 720 on frame 250 (final frame).
3. Setup the add-on
3. Start manager & local agent scripts
4. Hit "Run Animation Tasks"
5. Wait for forever
6. Get errors

### Expected behavior
Doesn't take too long to render, given it's a spinning default cube w/ multiple machines-worth of power. When it's done I have a series of PNGs or video, not a bunch of tasks with errors.

### Screenshots
![image](https://user-images.githubusercontent.com/34630441/151666786-a5979f0a-4330-4b2b-95b2-001df8725671.png)
![image](https://user-images.githubusercontent.com/34630441/151668705-f0678199-47af-4668-8075-ac68d89a9b81.png)
![image](https://user-images.githubusercontent.com/34630441/151668723-93e802f8-7e14-499a-8d02-f045651c3cca.png)
![image](https://user-images.githubusercontent.com/34630441/151668747-869b8dd9-6125-4790-a4ac-d3390c348166.png)

### Additional context
https://www.toptal.com/developers/hastebin/udixokivur.yaml
[logthing.txt](https://github.com/state-of-the-art/BlendNet/files/7964131/logthing.txt) (too big to just do a hastebin link)

**Comment by rabits** [comment]
Yeah, it's some sort of logic issue:
```
22.01.28 01:53:04.660000	  Traceback (most recent call last):
22.01.28 01:53:04.660000	    File "<string>", line 1, in <module>
22.01.28 01:53:04.660000	    File "C:\Users\Photon\Documents\dist\blendnet\BlendNet\script-compose.py", line 85, in <module>
22.01.28 01:53:04.660000	      image_node.layer = 'View Layer'
22.01.28 01:53:04.660000	  TypeError: bpy_struct: item.attr = val: enum "View Layer" not found in ('ViewLayer')
```

The script which tries to compose the result out of the rendered pieces fails... Need to check closely.

**Comment by rabits** [comment]
Working on reproducing the issue - so regarding the slowness, by default Blender v3 switched from "strict number of samples to render" to "noise threshold", means it tries to determine amount of noise in the scene and stop render when it hit the specific value. That leads to 1024 samples to render for a single cube in Blendnet, because it's nature to distribute the tasks by strict samples over the nodes and it can't calculate the noise threshold due to it's distributed architecture.

So the easy answer to that is not to use "noise threshold", the hard answer will be to change the Blendnet architecture to deal with this kind of workload and distribute as one frame per node. Unfortunately right now the task that should address this issue is quite stalled (#90), so not sure when I will rewrite the engine of Blendnet to support that.

**Comment by rabits** [comment]
Ok, just reproduced locally - that's a bug for sure.

**Comment by rabits** [comment]
Looks like v3 uses by default "ViewLayer" instead of "View Layer" as a name. Created a fix for that.

**Comment by rabits** [comment]
Will fix it for master and then move to v0.3

**Comment by rabits** [comment]
@Zman350x could you please check the fixed dev version please:
* https://2557-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.11-b7f06b2.zip
* https://2557-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.11-b7f06b2.tar.gz

**Comment by Zman350x** [comment]
@rabits I go to work on Tuesday, I'll try it then!

**Comment by rabits** [comment]
Thank you, and I would recommend to start small - like one manager + one agent + one image task and gradually move to bigger installations (2 agents + animation tasks, 4 agents and some real project).
