### ISSUE TITLE
[BUG] MacOSX unable to locate gcloud with running via Launcher

### ISSUE THREAD

**Issue by slatunje** [state-of-the-art/BlendNet#62]
### Issue description:
If Blender with BlendNet Addon is running from Launcher - it can't find the cloud provider tools. If running from console - it's working ok.

### Environment:
* **Application version**: 0.2.0, 0.3.0-dev
* **Blender client version**:  2.83.0
* ~**Blender worker version**: 2.83.0~
* **OS**: Mac OSX

### Steps to reproduce: in Terminal
Steps to reproduce the behaviou:
1. Run Blender via CLI
2. Open project
3. Edit > Preferences > Render: BlendNet
4. Scroll down to Provider
5. I see default provider as expected

### Expected behavior
Selects default provider as expected

### Screenshots
![Screenshot 2020-09-07 at 13 46 17](https://user-images.githubusercontent.com/2518656/92389284-b6fc9a00-f110-11ea-8202-403fd831df53.png)

### Steps to reproduce: Launcher Start
Steps to reproduce the behaviour:
1. Run Blender via Launcher e.g non-cli
2. Open project
3. Edit > Preferences > Render: BlendNet
4. Scroll down to Provider
5. I see error `gcp - ERROR: unable to initialize`

### Expected behavior
I expected to see the default provider

### Screenshots
![Screenshot 2020-09-07 at 13 22 34](https://user-images.githubusercontent.com/2518656/92389050-39388e80-f110-11ea-9bdb-8e1d0cf09593.png)

### Additional context
Even after exporting `GOOGLE_CLOUD_SDK_ROOT ` as assumed here https://github.com/state-of-the-art/BlendNet/blob/d0c182486be88eed476c61f1d4af7caeb1461d93/BlendNet/providers/gcp/__init__.py#L64

It still doesn't find the GOOGLE_CLOUD_SDK_ROOT

Will it not be a good idea to some how read GOOGLE_CLOUD_SDK_ROOT envar in GUI context?

I can confirm the behaviours are the same even when providers are switched to AWS

**Comment by rabits** [comment]
Hello @slatunje - it's slightly confusing... There is no 0.3.0 version available, the one is existing is 0.3.0-development from the master branch and the release one is 0.2.0. It's in active development so bugs are expected.

Anyway, regarding the issue - looks like you did not setup the gcloud (gcp sdk) correctly. Make sure you [followed all the steps in wiki](https://github.com/state-of-the-art/BlendNet/wiki/HOWTO:-Setup-provider:-Google-Cloud-Platform-(GCP)) , especially the ones about put the proper system PATH env variables. You just need to put path to gcp sdk bin dir in your system PATH.

The way GCP provider is working - it check the `gcloud` command available and getting the SDK path from it. So it's necessary right now to properly set your PATH - system env variable.

**Comment by rabits** [comment]
So if you can provide more information - what is the PATH for cli and Launcher, and check your system settings (I belive Launcher should provide the system PATH was set for the user) - that will be really great

**Comment by rabits** [comment]
And one more about `GOOGLE_CLOUD_SDK_ROOT` - if it is set in the env, probably PATH is also was changed, right? I mean if the gcloud installer set `GOOGLE_CLOUD_SDK_ROOT` variable and it's accessible from Launcher - probably the changed PATH variable should be here too...

**Comment by slatunje** [comment]
> Thank you for the bug reporting, but it's slightly confusing... There is no 0.3.0 version available, the one is existing is 0.3.0-development from the master branch

correct was using the master branch

> Anyway, regarding the issue - looks like you did not setup the gcloud (gcp sdk) correctly. Make sure you [followed all the steps in wiki](https://github.com/state-of-the-art/BlendNet/wiki/HOWTO:-Setup-provider:-Google-Cloud-Platform-(GCP)) , especially the ones about put the proper system PATH env variables. You just need to put path to gcp sdk bin dir in your system PATH.

For clarity sake, all terminal execution works as expected on both AWS & GCP. I used https://github.com/state-of-the-art/BlendNet/wiki/files/blendnet-test-project-2.82-v0.2.zip

For example if I execute `/Applications/Blender.app/Contents/MacOS/Blender` on terminal and render via blendnet addon using above blendfile then **every thing works as expected** and it downloads back into my local directory. I think this is an awesome project.

### Terminal shows:

```
INFO: Found provider "gcp"
INFO: Found google cloud sdk: /Users/Blender/Applications/Google/google-cloud-sdk
DEBUG: Loading gcloud paths
INFO: Found provider "local"
INFO: Found provider "aws"
INFO: Found aws tool: /usr/local/bin/aws
WARN: Metadata is not available
INFO: Set region for aws tool: eu-west-2
INFO: Importing base from "local" provider
DEBUG: selected provider: gcp
```

### Success Scenario

I should also mention that I was able to successfully **render via aws via terminal** and this too works as expected

I should point out that I previously had `aws` and `gcloud` set up on my system, as I use them daily with terraform to do some other cloud related work. 

I also followed the steps to make sure nothing was missing.

For this reason, I can assume that gcp and aws are setup to work correctly. 

### Extra Config Data

bash_profile shows

```bash
if [ -f '/Users/Blender/Applications/Google/google-cloud-sdk/path.bash.inc' ]; then . '/Users/Blender/Applications/Google/google-cloud-sdk/path.bash.inc'; fi
if [ -f '/Users/Blender/Applications/Google/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/Blender/Applications/Google/google-cloud-sdk/completion.bash.inc'; fi
```

`gcloud info` shows correct path, I will only give relevant data here, let me know if you need more.

```bash
Google Cloud SDK [308.0.0]

System PATH: [/Users/Blender/Applications/Google/google-cloud-sdk/bin:  ... ]
Cloud SDK on PATH: [True]
Kubectl on PATH: [/usr/local/bin/kubectl]

Installation Root: [/Users/Blender/Applications/Google/google-cloud-sdk]
User Config Directory: [/Users/Blender/.config/gcloud

Installation Properties: [/Users/Blender/Applications/Google/google-cloud-sdk/properties]

User Config Directory: [/Users/Blender/.config/gcloud]

Active Configuration Path: [/Users/Blender/.config/gcloud/configurations/config_blender]
Logs Directory: [/Users/Blender/.config/gcloud/logs]
Last Log File: [/Users/Blender/.config/gcloud/logs/2020.09.08/04.15.11.692958.log]
```

> The way GCP provider is working - it check the `gcloud` command available and getting the SDK path from it. So it's necessary right now to properly set your PATH - system env variable.

```
~ $printenv | grep Google
PATH=/Users/Blender/Applications/Google/google-cloud-sdk/bin: ..........
```

### Failure Scenario

As described in initial issue report. I am not familia in how to capture the same console output, when launching via launcher. 

### Summary

I hope I have provided enough information.

I think the issue has something todo with how the path is read when launched via launcher.  I suspect directory path might need escaping. I will dig in further when I get the time.

Thanks

**Comment by rabits** [comment]
Hi @slatunje , thank you for the details)

So the thing here - it's not just about the terminal. Of course terminal uses your bash profile & settings, but in MacOS should be some place with the system-wide env settings, it should include launcher application too, as well as the terminal. Unfortunately I have no macbook to check it out, but I think you can check the next files:
```
cat ~/.profile
cat /etc/profile
```
For sure Launcher will not use the bash profile, but probably could use ~/.profile or the system /etc/profile. Could you check that please? That could require reboot. Also probably you can try to reinstall gcp sdk - as a last resort.

**Comment by rabits** [comment]
This answer looks interesting: https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x#answer-135697 - just edit the `~/.MacOSX/environment.plist` file if it's existing or try the commands - I think the commands like launchctl will set the env for all the users and `~/.MacOSX/environment.plist` is just for your user.

Also this could require reboot

**Comment by slatunje** [comment]
@rabits since my mac is configured with various users, I am trying to avoid system wide environment settings.

I don't normally use `.profile` but I will try it out later and let you know after both re-login and rebooting.

> This answer looks interesting: https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x#answer-135697 - just edit the `~/.MacOSX/environment.plist` file if it's existing or try the commands - I think the commands like launchctl will set the env for all the users and `~/.MacOSX/environment.plist` is just for your user.
> 
> Also this could require reboot

I saw this solution earlier and after reading through the many suggested solutions, I will try out a simpler approach inspired by [osx-env-sync](https://github.com/ersiner/osx-env-sync#usage) repo

The idea is to setup specific environments that blendnet needs, so as to not overload GUI apps with unnecessary envars.

I will also try out combination of `launchctl` with `~/Library/LaunchAgents/blend-addon-blendnet.plist` to see if this can work.

**Comment by rabits** [comment]
Hi @slatunje 

Yeah agree, it's not good to set some envs for the whole system. But modifying of `~/.MacOSX/environment.plist` PATH is not going to add additional envvar, just a path (last resort in case PATH=$PATH:<path_to_gcp_sdk_bin>) to the existing PATH envvar. This way you probably can get rid of modification of PATH in your profile/bash profile.

If some of the ways will work - I will be glad to add such notification to the wiki for mac users.

**Comment by rabits** [comment]
Will move to 0.4 due to no updates. And the issue have a workaround - to run blender from console.

**Comment by rabits** [comment]
@ErwanMAS proposed a way to allow user to specify the path in UI for provider if binary was not found - I think that could work... Need to check how to properly inject it.

**Comment by timpharo** [comment]
Has there been much more progress on this? I would love to render my animation with cycles instead of we've and can't wait to try this plugin out using my mac

**Comment by rabits** [comment]
Hi @timpharo - you don't actually need to wait, there is a couple of workarounds - the most simple one is to run blender from terminal (where PATH is set to the place where gcloud bin is located).

I already prepared a semi-working solution, but need to make sure it will be properly displayed on UI. That actually introduces the providers configuration, so could take some time to test the change properly... I think this weekend I can present the change and work on merging to the master and further v0.4 :)

**Comment by timpharo** [comment]
> Hi @timpharo - you don't actually need to wait, there is a couple of workarounds - the most simple one is to run blender from terminal (where PATH is set to the place where gcloud bin is located).
> 
> I already prepared a semi-working solution, but need to make sure it will be properly displayed on UI. That actually introduces the providers configuration, so could take some time to test the change properly... I think this weekend I can present the change and work on merging to the master and further v0.4 :)

Thanks @rabits, i will try the workaround and look forward to v0.4 👍

**Comment by rabits** [comment]
Finally completed initial debug of the changes - need to test them on win and mac too.

**Comment by rabits** [comment]
Now the user can choose the gcloud/aws tool path right from the addon prefs interface and it will be saved in settings. It's affecting only UI and by default it still trying to find the required tool in the PATH.
