### ISSUE TITLE
Describe and demo video for the next release

### ISSUE THREAD

**Issue by state-of-the-art** [state-of-the-art/BlendNet#7]
We need a clear video that will show the whole process of the BlendNet create project, install addon and usage process. It should show how it's working in the real life with a number of frames.

Proposed in #5

**Comment by rabits** [comment]
The main obstacle right now - is to get the preemptible CPUs for testing. GCP seems changed their policy and not giving them without contacting sales.

**Comment by rabits** [comment]
Yep, all the roads going to sales - and I think it's too hard for user to follow this path, so need to find a workaround, for example - bring ability to use regular CPUs for agents if preemptible ones is not available.

**Comment by rabits** [comment]
Ok, now #37 is implemented - it's a way out of this sales nightmare

**Comment by rabits** [comment]
Also improved errors with modules initialization - now user will be properly notified if something is going wrong.

**Comment by rabits** [comment]
The video was released - https://youtu.be/VGZvweh1tb4
